version: "3.9"

services:
  app:
    container_name: wallet-app
    build: .
    ports:
      - "3010:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"
